[book]
authors = ["Ashish Patel"]
language = "en"
src = ""
title = "Wiki"
description = "Personal wiki"

[build]
build-dir = "book"
create-missing = false

[output.html.fold]
enable = true
level = 0

[output.html]
additional-js = ["./theme/mermaid.min.js", "./theme/mermaid-init.js", "./theme/custom.js"]
mathjax-support = true
default-theme = "latte"
preferred-dark-theme = "latte"
additional-css = ["./theme/graphite-tokens.css","./theme/graphite-content.css","./theme/graphite-chrome.css","./theme/ashish.css"]
no-section-label = true
git-repository-url = "https://github.com/ashishdotme/notes"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/ashishdotme/notes/edit/master{path}"
site-url = "https://wiki.ashish.me"
sidebar-header-nav= false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.embedify]
scroll-to-top.enable = true

footer.enable = false
footer.message = "Copyright © 2024 • Created with ❤️ by [Ashish Patel](https://ashish.me)"

[preprocessor.random]
command = "python3 build_index.py"
